language: cpp
addons:
  apt:
    packages:
      - clang # to get an updated version including scan-build
      - cmake
      - cmake-data
      - cppcheck
      - ninja-build
    sources:
      - george-edison55-precise-backports
compiler:
  - clang
  - gcc
env:
  - ANALYZE=1
  - CMAKE_CXX_STANDARD=98
  - CMAKE_CXX_STANDARD=11
script:
  - ./.travis.sh
