language: cpp
addons:
  apt:
    packages:
      - clang # to get an updated version including scan-build
      - cmake
      - cmake-data
      - cppcheck
      - ninja-build
    sources:
      - george-edison55-precise-backports
compiler:
  - clang
  - gcc
env:
  - CTEST_OUTPUT_ON_FAILURE=ON ANALYZE=1
  - CTEST_OUTPUT_ON_FAILURE=ON ANALYZE=
script:
  - ./.travis.sh
