language: cpp
dist: trusty
addons:
  apt:
    packages:
      - clang # to get an updated version including scan-build
      - cmake
      - cmake-data
      - cppcheck
      - g++-4.7
      - ninja-build
    sources:
      - george-edison55-precise-backports
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CMAKE_CXX_STANDARD=11
  - CMAKE_CXX_STANDARD=14
matrix:
  exclude:
    - compiler: clang
      env: CPPCHECK=yes
    - os: osx
      env: CPPCHECK=yes
    - os: osx
      compiler: gcc
    - compiler: gcc
      env: CMAKE_CXX_STANDARD=14
before_install:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update && brew install ninja; fi
script:
  - ./.travis.sh
