language: cpp
addons:
  apt:
    packages:
      - cmake
      - cmake-data
    sources:
      - george-edison55-precise-backports
compiler:
  - clang
  - gcc
before_script:
  - cmake -E make_directory build
script:
  - cmake -E chdir build cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} ..
  - cmake --build build
  - CTEST_OUTPUT_ON_FAILURE=ON cmake --build build --target test
