language: cpp
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - ninja-build
    sources:
      - george-edison55-precise-backports
compiler:
  - clang
  - gcc
env:
  - CTEST_OUTPUT_ON_FAILURE=ON
before_script:
  - cmake -E make_directory build
script:
  - cmake -E chdir build cmake -G Ninja ..
  - cmake --build build
  - cmake --build build --target test
