language: cpp
addons:
  apt:
    packages:
      - clang # to get an updated version including scan-build
      - cmake
      - cmake-data
      - cppcheck
      - ninja-build
    sources:
      - george-edison55-precise-backports
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CMAKE_CXX_STANDARD=98
  - CMAKE_CXX_STANDARD=11
  - CPPCHECK=1
matrix:
  exclude:
    - compiler: clang
      env: CPPCHECK=1
    - os: osx
      env: CPPCHECK=1
    - os: osx
      compiler: gcc
before_install:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update && brew install ninja; fi
script:
  - ./.travis.sh
